config/routes.rb
DadsBank::Application.routes.draw do

  match 'login' => 'login#index', :as => :login
  match 'logout' => 'login#logout', :as => :logout
  match 'login/authenticate' => 'login#authenticate'

  match 'account' => 'accounts#show'
  root :to => 'login#index'

  resources :bank do
    resources :accounts
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  include Login
  attr_accessible :name, :bank_id, :allowance

  belongs_to :bank
  has_many :transactions

  validates_presence_of :bank_id, :name
  
  def balance 
    self.transactions.size > 0 && self.transactions.last.balance || 0.0
  end

  def apply_interest
    rate = self.bank.daily_interest_rate
    credit_amount = balance * (rate / 100) 
    credit(credit_amount,"Daily interest calculated at #{rate.to_f.round(4)}")
  end

  def apply_allowance
    a = self.allowance
    credit(a, "Allowance of #{a} applied")
  end

  def credit(amount, description = nil)
    transact(amount,description){ balance + amount }
  end

  def debit(amount, description = nil)
    transact(amount,description){ balance - amount }
  end

  def self.authenticate(n,p)
    if ( acc = Account.find_by_name(n) ) 
      return acc if acc.hashed_password == Login.hash_password(p,acc.salt) 
    end 
    nil
  end

  private

  def transact(amount, description, &block)
    new_balance = yield
    Transaction.create(
      :account_id => self.id,
      :amount => amount,
      :balance => new_balance,
      :description => description
    )
  end

end

app/models/bank.rb
class Bank < ActiveRecord::Base
  include Login
  attr_accessible :interest_period, :interest_rate, :name  

  validates :interest_period, :inclusion => {:in => %w{weekly monthly yearly}}
  validates :interest_rate, :numericality => true
  validates_presence_of :hashed_password, :salt, :name

  has_many :accounts

  def daily_interest_rate
    case self.interest_period
    when 'weekly'
      self.interest_rate / (365.0 / 7.0)  
    when 'monthly'
      self.interest_rate / (365.0 / 12.0) 
    when 'yearly'
      self.interest_rate / 365.0 
    else
      raise "Interest period not valid"
    end
  end

  def interest_readable
    "#{interest_rate}% #{interest_period.capitalize}"
  end

  def self.authenticate(n,p)
    if ( bank = Bank.find_by_name(n) ) 
      if bank.hashed_password == Login.hash_password(p,bank.salt) 
        return bank 
      end
    end 
    nil
  end

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  attr_accessible :amount, :balance, :description, :account_id
  belongs_to :account
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_filter :load_bank, :except => :show

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.find_all_by_bank_id(@bank.id)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    if (acc = session[:account])
      @account = Account.find(acc)
      @bank = Bank.find(@account.bank_id)
    elsif load_bank
      @account = Account.find(params[:id])
    else
      flash[:alert] = "Invalid account details"
      redirect_to :root and return
    end

    @chart_data = [["Time","Balance"]].concat(
      @account.transactions.map{|t| [t.created_at, t.balance.to_f.round(2)] }
    )

    respond_to do |format|
      format.html # show.html.erba
      format.json { render :json => @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new(:bank_id => @bank.id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new( 
      :name => params[:account][:name],
      :allowance => params[:account][:allowance],
      :password => params[:account][:password],
      :bank_id => @bank.id)

    respond_to do |format|
      if @account.save
        format.html { redirect_to bank_accounts_path(@bank), :notice => 'Account was successfully created.' }
        format.json { render :json => @account, :status => :created, :location => @account }
      else
        format.html { render :action => "new" }
        format.json { render :json => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])
    @account.name = params[:account][:name]
    @account.allowance = params[:account][:allowance]
    @account.password = params[:account][:password] unless params[:account][:password].length == 0
    
    respond_to do |format|
      if @account.save
        format.html { redirect_to bank_accounts_path(@bank), :notice => 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy 

    respond_to do |format|
      format.html { redirect_to bank_accounts_path(@bank) }
      format.json { head :no_content }
    end
  end

  private

  def load_bank
    if session[:bank].nil?
      flash[:error] = "Not logged in."
      redirect_to :login 
    else
      @bank = Bank.find(session[:bank])
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def login
    render :login
  end

  def logout
    reset_session
    redirect_to :root
  end

  def authenticate
    un,pw = request[:name],request[:password]
    if (acct = Account.authenticate(un,pw))
      session[:account] = acct
      redirect_to :account and return
    elsif (bank = Bank.authenticate(un,pw))
      session[:bank] = bank 
      redirect_to bank_accounts_path(bank) and return
    else
      flash[:error] = "Invalid login details"
      redirect_to :login
    end
  end


end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/accounts/_form.html.erb
<div class="span10">

  <%= form_for([@bank,@account], :html => {:class => 'form-horizontal'}) do |f| %>

  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h5>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <fieldset>
      <legend><%= form_title %></legend>

      <div class="control-group">
        <%= f.label :name, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :name %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :allowance, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :allowance %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :password, :class => 'control-label' %>
        <div class="controls">
          <%= f.password_field :password %>
        </div>
      </div>

      <div class="form-actions">
        <%= f.submit "Save Account", :class => 'btn btn-primary' %>
        <%= link_to 'Cancel', bank_accounts_path(@bank), :class => 'btn' %>
      </div>

    </fieldset>
<% end %>

</div>

app/views/accounts/edit.html.erb
<div class="span10">
  <h1><%= @bank.name %></h1>
</div>

<%= render 'form', :form_title => "Edit Account Details" %>

app/views/accounts/index.html.erb
<div class="span10">
  <h1><%= @bank.name %></h1>
</div>

<div class="span10">
  <h2>Accounts</h2>
</div>

<div class="span10">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Name</th>
      <th>Allowance</th>
      <th>Balance</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @accounts.each do |account| %>
    <tr>
      <td><%= account.name %></td>
      <td><%= number_to_currency(account.allowance) %></td>
      <td><%= number_to_currency(account.balance) %></td>
      <td><%= link_to 'Show', bank_account_path(@bank,account), :class => 'btn' %></td>
      <td><%= link_to 'Edit', edit_bank_account_path(@bank,account), :class => 'btn btn-info' %></td>
      <td><%= link_to 'Destroy', [@bank, account], :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-danger' %></td>
    </tr>
  <% end %>
  </tbody>
  </table>
</div>

<div class="span10">

  <%= link_to 'Create New Account', new_bank_account_path(@bank), :class => 'btn btn-primary' %>

</div>

app/views/accounts/new.html.erb
<div class="span10">
  <h1><%= @bank.name %></h1>
</div>

<%= render 'form', :form_title => "Create New Account" %>

app/views/accounts/show.html.erb
<div class="well span6">
  <h1><small><%= @account.bank.name %>:</small> <%= @account.name %></h1>
</div>

<div class="well span5">
  <h1><small>allowance</small> <%= number_to_currency(@account.allowance) %></h1>
</div>

<div class="well span6">
  <h1><small>balance</small> <span class="money"><%= number_to_currency(@account.balance) %></span></h1>
</div>

<div class="well span5">
  <h1><small>interest rate</small> <%= @account.bank.interest_readable %></h1>
</div>


<p id="notice"><%= notice %></p>


<div id="chart_div" style="width: 100%; height: 300px; position:relative; left:10px; clear:both;"></div>

<div class="span12">
  <table class="table table-striped" id="transactions">
    <thead>
    <tr>
      <th>When</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Balance</th>
    </tr>
    </thead>
    <tbody>
    <% @account.transactions.reverse.each do |transaction| %>
    <tr>
      <td><%= transaction.created_at %></td>
      <td><%= transaction.description %></td>
      <td><%= number_to_currency(transaction.amount, :precision => 4) %></td>
      <td><%= number_to_currency(transaction.balance) %></td>
    </tr>
    <% end %>
    </tbody>
  </table>
</div>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  /* https://developers.google.com/chart/interactive/docs/gallery/linechart */
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = google.visualization.arrayToDataTable(<%= @chart_data.to_json.html_safe %>);
    var options = {
      lineWidth: 6,
      colors: ['green','blue'],
      legend: {position: 'none'},
      hAxis: {textPosition: 'none'},
      vAxis: {format: '$#', textPosition: 'in'},
      chartArea:{left:0,top:0,width:"100%",height:"100%"}
    };
    var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
    chart.draw(data, options);
  };


</script>
<script type="text/javascript">

  $.extend( $.fn.dataTableExt.oStdClasses, {
    "sWrapper": "dataTables_wrapper form-inline"
    });

  $.extend( $.fn.dataTableExt.oStdClasses, {
    "sSortAsc": "header headerSortDown",
    "sSortDesc": "header headerSortUp",
    "sSortable": "header"
  });

  // datatables
  $(document).ready(function() {
    $('#transactions').dataTable({
      "aoColumnDefs": [ 
        { "bSortable": true, "aTargets": [ 0 ] },
        { "bSortable": false, "aTargets": [1,2,3] }
      ],
      "sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
      "sPaginationType": "bootstrap"
    });
  });

</script>

app/views/common/_flashes.html.erb
<% unless flash[:notice].blank? %>
  <div class="alert alert-info span11">
    <%= flash[:notice] %>
    <a class="close" data-dismiss="alert" href="#">&times;</a> 
  </div>
<% end %>

<% unless flash[:error].blank? %>
  <div class="alert alert-error span11">
    <%= flash[:error] %>
    <a class="close" data-dismiss="alert" href="#">&times;</a> 
  </div>
<% end %>

<% unless flash[:alert].blank? %>
  <div class="alert alert-warning span11">
    <%= flash[:alert] %>
    <a class="close" data-dismiss="alert" href="#">&times;</a> 
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DadsBank</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="body" class="container">
    <div class="row">

      <%= render :partial => 'common/flashes' %>

      <%= yield %>

    </div>

  </div>


</body>
</html>

app/views/login/index.html.erb
<div class="span10">
  <h2>Login</h2>
</div>

<div class="span10">
  <%= form_tag("/login/authenticate", :method => 'post', :html => {:class => 'form-vertical'}) do %> 

    <%= label_tag :name %>
    <%= text_field_tag :name %>

    <%= label_tag :password %>
    <%= password_field_tag :password %>

    <div>
      <%= submit_tag "Login", :class => "btn btn-primary " %>
    </div>

  <% end %>
</div>